<a href="https://colab.research.google.com/github/akshat-shethia/Data_Science_AIML/blob/master/Machine_Learning_A_To_Z/Google_Collab_Files/Data_Pre_Processing/Section_3_Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing all the important libraries

In [50]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd

In [51]:
df = pd.read_csv("/content/Data.csv")
df.head()
df.dtypes

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

## Splitting into `X` and `Y`

In [52]:
X = df.drop("Purchased",axis = 1)
Y = df["Purchased"]
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

## Filling all the missing values

In [53]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = "mean")
cols = ["Age", "Salary"]
imputed_df = imputer.fit_transform(X[cols])
X[cols] = imputed_df
X.isna().sum()
X

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

## Encoding Categorical Data

In [56]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

cat_cols = ['Country']
column_transformer = ColumnTransformer([("onehot",OneHotEncoder(),[0])],remainder = "passthrough")
X = np.array(column_transformer.fit_transform(X))

X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [57]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## Splitting Data into Train and Test

In [58]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2)
X_train[0]

array([1.0e+00, 0.0e+00, 0.0e+00, 4.8e+01, 7.9e+04])

## Feature Scaling

In [63]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X_train[:,3:] = ss.fit_transform(X_train[:,3:])
X_test[:,3:] = ss.transform(X_test[:,3:]) #Here its only transform since were transforming
# on the basis of the vals in the training dataset
X_train

array([[ 1.        ,  0.        ,  0.        ,  1.63085062,  1.73588681],
       [ 0.        ,  1.        ,  0.        , -1.15751667, -0.77584652],
       [ 0.        ,  1.        ,  0.        ,  0.39157627,  0.2065203 ],
       [ 1.        ,  0.        ,  0.        ,  1.01121345,  1.03260148],
       [ 0.        ,  0.        ,  1.        ,  0.20224269, -0.97678518],
       [ 1.        ,  0.        ,  0.        , -0.07315161,  0.53025481],
       [ 0.        ,  0.        ,  1.        , -1.62224455, -1.37866251],
       [ 1.        ,  0.        ,  0.        , -0.3829702 , -0.37396918]])