In [1]:
import numpy as np

## DATATYPES AND ATTRIBUTES


In [2]:
#Numpy's main dataType is ndarray
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [3]:
array2 = np.array([[1.1,2,3],
                 [4,5,6],
                 [7,8,9]])
array2

array([[1.1, 2. , 3. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

In [4]:
array3 = np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                   [[1,2,3],
                    [4,5,6],
                    [7,8,9]]])
array3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [5]:
type(array1)

numpy.ndarray

In [6]:
array1.ndim,array2.ndim,array3.ndim

(1, 2, 3)

In [7]:
array1.size,array2.size,array3.size

(3, 9, 18)

In [8]:
array1.dtype,array2.dtype,array3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [9]:
type(array1),type(array2),type(array3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create A Dataframe from NumPy array

In [10]:
import pandas as pd
df = pd.DataFrame(array2)
df

0    1    2
0  1.1  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0

## Creating Arrays

In [11]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [12]:
sample_array.dtype

dtype('int32')

In [13]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
ones.dtype
type(ones)

numpy.ndarray

In [15]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
range_array = np.arange(0,10,2) # Start, Stop, Step
range_array

array([0, 2, 4, 6, 8])

In [17]:
random_array = np.random.randint(0,10,size = (3,3))
random_array

array([[8, 8, 3],
       [7, 1, 6],
       [0, 6, 0]])

In [18]:
random_array.size

9

In [19]:
random_array.shape

(3, 3)

In [20]:
random_array_float = np.random.random((5,3)) #Extra brackets to indicate the shape to be formed
random_array_float

array([[0.51959625, 0.52604188, 0.96167123],
       [0.50582866, 0.4594523 , 0.85288576],
       [0.62049347, 0.6697024 , 0.57963617],
       [0.55544614, 0.97772903, 0.82548406],
       [0.25217507, 0.7608671 , 0.84135842]])

In [21]:
random_array_float2 = np.random.rand(5,3) #Only rows and columns are to be mentioned
random_array_float2

array([[0.5505116 , 0.13383053, 0.58062873],
       [0.65207776, 0.03613946, 0.11111259],
       [0.41209957, 0.89797093, 0.15897015],
       [0.89771377, 0.60796736, 0.21814263],
       [0.71148376, 0.42986704, 0.33882595]])

## Creating Non Random-Random Numbers using `np.random.seed()`

## All the previosuly generated arrays contain **pseudo random numbers** ( this can be verified using the `np.random.seed()` function

We use the `np.random.seed(seed = 0)` function when we **dont** want our random values generated to change ever again

In [22]:
np.random.seed(0) # Now these values will never change
random_array_seed = np.random.randint(10,size = (5,3))
random_array_seed

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Different ways of viewing arrays and matrices

In [23]:
np.unique(random_array_seed)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
array1[0]

1

In [25]:
array2[0]

array([1.1, 2. , 3. ])

In [26]:
array3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
array3[:2,:2,:2]

array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])

In [28]:
rand_array = np.random.randint(0,50,size = (2,3,4,5))
rand_array

array([[[[38, 39, 23, 46, 24],
         [17, 37, 25, 13,  8],
         [ 9, 20, 16,  5, 15],
         [47,  0, 18, 35, 24]],

        [[49, 29, 19, 19, 14],
         [39, 32,  1,  9, 32],
         [31, 10, 23, 35, 11],
         [28, 34,  0,  0, 36]],

        [[ 5, 38, 40, 17, 15],
         [ 4, 41, 42, 31,  1],
         [ 1, 39, 41, 35, 38],
         [11, 46, 18, 27,  0]]],


       [[[14, 35, 12, 42, 20],
         [11,  4,  6,  4, 47],
         [ 3, 12, 36, 40, 14],
         [15, 20, 35, 23, 15]],

        [[13, 21, 48, 49,  5],
         [41, 35,  0, 31,  5],
         [30,  0, 49, 36, 34],
         [48, 29,  3, 34, 42]],

        [[13, 48, 39, 21,  9],
         [ 0, 10, 43, 23,  2],
         [34, 35, 30,  3, 18],
         [46, 35, 20, 17, 27]]]])

In [29]:
rand_array.shape, rand_array.ndim

((2, 3, 4, 5), 4)

In [30]:
#To get the first number of the inner most array
rand_array[:,:,:,:1]

array([[[[38],
         [17],
         [ 9],
         [47]],

        [[49],
         [39],
         [31],
         [28]],

        [[ 5],
         [ 4],
         [ 1],
         [11]]],


       [[[14],
         [11],
         [ 3],
         [15]],

        [[13],
         [41],
         [30],
         [48]],

        [[13],
         [ 0],
         [34],
         [46]]]])

## Manipulating Arrays and Comparing Arrays

### Arithmetic

In [31]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [32]:
array1

array([1, 2, 3])

In [33]:
array2

array([[1.1, 2. , 3. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

In [34]:
array2 * array1

array([[ 1.1,  4. ,  9. ],
       [ 4. , 10. , 18. ],
       [ 7. , 16. , 27. ]])

In [35]:
array1 + ones

array([2., 3., 4.])

In [36]:
array1 - ones

array([0., 1., 2.])

In [37]:
array1 * ones

array([1., 2., 3.])

In [38]:
array3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [40]:
array3 * array2

array([[[ 1.1,  4. ,  9. ],
        [16. , 25. , 36. ],
        [49. , 64. , 81. ]],

       [[ 1.1,  4. ,  9. ],
        [16. , 25. , 36. ],
        [49. , 64. , 81. ]]])